# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(413, 664)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header_label = QtGui.QLabel(Dialog)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setWeight(75)
        font.setBold(True)
        self.header_label.setFont(font)
        self.header_label.setAlignment(QtCore.Qt.AlignCenter)
        self.header_label.setMargin(10)
        self.header_label.setObjectName("header_label")
        self.verticalLayout.addWidget(self.header_label)
        self.main_tab_widget = QtGui.QTabWidget(Dialog)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_tab_widget.sizePolicy().hasHeightForWidth())
        self.main_tab_widget.setSizePolicy(sizePolicy)
        self.main_tab_widget.setObjectName("main_tab_widget")
        self.render_settings_tab = QtGui.QWidget()
        self.render_settings_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.render_settings_tab.setObjectName("render_settings_tab")
        self.mysterious = QtGui.QVBoxLayout(self.render_settings_tab)
        self.mysterious.setSpacing(0)
        self.mysterious.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.mysterious.setContentsMargins(10, 0, 0, 0)
        self.mysterious.setObjectName("mysterious")
        self.label_layout = QtGui.QVBoxLayout()
        self.label_layout.setSpacing(20)
        self.label_layout.setContentsMargins(-1, 20, -1, 20)
        self.label_layout.setObjectName("label_layout")
        self.label = QtGui.QLabel(self.render_settings_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setMargin(0)
        self.label.setObjectName("label")
        self.label_layout.addWidget(self.label)
        self.mysterious.addLayout(self.label_layout)
        self.render_globals_gbox = QtGui.QGroupBox(self.render_settings_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_globals_gbox.sizePolicy().hasHeightForWidth())
        self.render_globals_gbox.setSizePolicy(sizePolicy)
        self.render_globals_gbox.setMinimumSize(QtCore.QSize(0, 150))
        self.render_globals_gbox.setObjectName("render_globals_gbox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.render_globals_gbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.config_render_settings_button = QtGui.QPushButton(self.render_globals_gbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_render_settings_button.sizePolicy().hasHeightForWidth())
        self.config_render_settings_button.setSizePolicy(sizePolicy)
        self.config_render_settings_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_render_settings_button.setObjectName("config_render_settings_button")
        self.verticalLayout_4.addWidget(self.config_render_settings_button)
        self.config_image_file_prefix_button = QtGui.QPushButton(self.render_globals_gbox)
        self.config_image_file_prefix_button.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_image_file_prefix_button.sizePolicy().hasHeightForWidth())
        self.config_image_file_prefix_button.setSizePolicy(sizePolicy)
        self.config_image_file_prefix_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_image_file_prefix_button.setObjectName("config_image_file_prefix_button")
        self.verticalLayout_4.addWidget(self.config_image_file_prefix_button)
        self.mysterious.addWidget(self.render_globals_gbox)
        self.render_settings_gbox = QtGui.QGroupBox(self.render_settings_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_settings_gbox.sizePolicy().hasHeightForWidth())
        self.render_settings_gbox.setSizePolicy(sizePolicy)
        self.render_settings_gbox.setMinimumSize(QtCore.QSize(0, 150))
        self.render_settings_gbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.render_settings_gbox.setObjectName("render_settings_gbox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.render_settings_gbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.config_arnold_button = QtGui.QPushButton(self.render_settings_gbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_arnold_button.sizePolicy().hasHeightForWidth())
        self.config_arnold_button.setSizePolicy(sizePolicy)
        self.config_arnold_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_arnold_button.setObjectName("config_arnold_button")
        self.verticalLayout_5.addWidget(self.config_arnold_button)
        self.config_redshift_button = QtGui.QPushButton(self.render_settings_gbox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_redshift_button.sizePolicy().hasHeightForWidth())
        self.config_redshift_button.setSizePolicy(sizePolicy)
        self.config_redshift_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_redshift_button.setObjectName("config_redshift_button")
        self.verticalLayout_5.addWidget(self.config_redshift_button)
        self.mysterious.addWidget(self.render_settings_gbox)
        self.main_tab_widget.addTab(self.render_settings_tab, "")
        self.configs_tab = QtGui.QWidget()
        self.configs_tab.setObjectName("configs_tab")
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.configs_tab)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.configs_plaint_text = QtGui.QPlainTextEdit(self.configs_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configs_plaint_text.sizePolicy().hasHeightForWidth())
        self.configs_plaint_text.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setWeight(50)
        font.setBold(False)
        self.configs_plaint_text.setFont(font)
        self.configs_plaint_text.setStyleSheet("")
        self.configs_plaint_text.setTextInteractionFlags(QtCore.Qt.TextSelectableByMouse)
        self.configs_plaint_text.setObjectName("configs_plaint_text")
        self.verticalLayout_2.addWidget(self.configs_plaint_text)
        self.config_file_label = QtGui.QLabel(self.configs_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.config_file_label.sizePolicy().hasHeightForWidth())
        self.config_file_label.setSizePolicy(sizePolicy)
        self.config_file_label.setWordWrap(True)
        self.config_file_label.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.config_file_label.setObjectName("config_file_label")
        self.verticalLayout_2.addWidget(self.config_file_label)
        self.verticalLayout_3.addLayout(self.verticalLayout_2)
        self.main_tab_widget.addTab(self.configs_tab, "")
        self.verticalLayout.addWidget(self.main_tab_widget)

        self.retranslateUi(Dialog)
        self.main_tab_widget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "The Current Sgtk Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.header_label.setText(QtGui.QApplication.translate("Dialog", "Project/Studio Default Configurations", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Click on any button below to configure or restore the studio/project\'s defaults.", None, QtGui.QApplication.UnicodeUTF8))
        self.render_globals_gbox.setTitle(QtGui.QApplication.translate("Dialog", "Common", None, QtGui.QApplication.UnicodeUTF8))
        self.config_render_settings_button.setText(QtGui.QApplication.translate("Dialog", "Config Render Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.config_image_file_prefix_button.setText(QtGui.QApplication.translate("Dialog", "Config Image File Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.render_settings_gbox.setTitle(QtGui.QApplication.translate("Dialog", "Renderers", None, QtGui.QApplication.UnicodeUTF8))
        self.config_arnold_button.setText(QtGui.QApplication.translate("Dialog", "Config Arnold Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.config_redshift_button.setText(QtGui.QApplication.translate("Dialog", "Config Redshift Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.render_settings_tab), QtGui.QApplication.translate("Dialog", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.configs_plaint_text.setPlainText(QtGui.QApplication.translate("Dialog", "Nothing to display", None, QtGui.QApplication.UnicodeUTF8))
        self.config_file_label.setText(QtGui.QApplication.translate("Dialog", "Config file: Z:Pipelinedevshotgridprojectspipeline_developmentcodedefconmayarender_settings.yaml", None, QtGui.QApplication.UnicodeUTF8))
        self.main_tab_widget.setTabText(self.main_tab_widget.indexOf(self.configs_tab), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
