# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialog.ui'
#
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from tank.platform.qt import QtCore, QtGui

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(478, 661)
        self.verticalLayout = QtGui.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtGui.QTabWidget(Dialog)
        self.tabWidget.setObjectName("tabWidget")
        self.config_tab = QtGui.QWidget()
        self.config_tab.setMinimumSize(QtCore.QSize(0, 0))
        self.config_tab.setObjectName("config_tab")
        self.mysterious = QtGui.QVBoxLayout(self.config_tab)
        self.mysterious.setSpacing(0)
        self.mysterious.setSizeConstraint(QtGui.QLayout.SetFixedSize)
        self.mysterious.setContentsMargins(10, 0, 0, 0)
        self.mysterious.setObjectName("mysterious")
        self.label = QtGui.QLabel(self.config_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label.setMargin(20)
        self.label.setObjectName("label")
        self.mysterious.addWidget(self.label)
        self.render_globals_gbox = QtGui.QGroupBox(self.config_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_globals_gbox.sizePolicy().hasHeightForWidth())
        self.render_globals_gbox.setSizePolicy(sizePolicy)
        self.render_globals_gbox.setMinimumSize(QtCore.QSize(0, 150))
        self.render_globals_gbox.setObjectName("render_globals_gbox")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.render_globals_gbox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.config_render_settings_button = QtGui.QPushButton(self.render_globals_gbox)
        self.config_render_settings_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_render_settings_button.setObjectName("config_render_settings_button")
        self.verticalLayout_4.addWidget(self.config_render_settings_button)
        self.config_image_file_prefix_button = QtGui.QPushButton(self.render_globals_gbox)
        self.config_image_file_prefix_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_image_file_prefix_button.setObjectName("config_image_file_prefix_button")
        self.verticalLayout_4.addWidget(self.config_image_file_prefix_button)
        self.mysterious.addWidget(self.render_globals_gbox)
        self.render_settings_gbox = QtGui.QGroupBox(self.config_tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.render_settings_gbox.sizePolicy().hasHeightForWidth())
        self.render_settings_gbox.setSizePolicy(sizePolicy)
        self.render_settings_gbox.setMinimumSize(QtCore.QSize(0, 150))
        self.render_settings_gbox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.render_settings_gbox.setObjectName("render_settings_gbox")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.render_settings_gbox)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.config_arnold_button = QtGui.QPushButton(self.render_settings_gbox)
        self.config_arnold_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_arnold_button.setObjectName("config_arnold_button")
        self.verticalLayout_5.addWidget(self.config_arnold_button)
        self.config_redshift_button = QtGui.QPushButton(self.render_settings_gbox)
        self.config_redshift_button.setMinimumSize(QtCore.QSize(0, 35))
        self.config_redshift_button.setObjectName("config_redshift_button")
        self.verticalLayout_5.addWidget(self.config_redshift_button)
        self.mysterious.addWidget(self.render_settings_gbox)
        self.tabWidget.addTab(self.config_tab, "")
        self.view_settings_tab = QtGui.QWidget()
        self.view_settings_tab.setObjectName("view_settings_tab")
        self.tabWidget.addTab(self.view_settings_tab, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtGui.QApplication.translate("Dialog", "The Current Sgtk Environment", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Dialog", "Click on any button below to configure or restore the studio/project\'s defaults.", None, QtGui.QApplication.UnicodeUTF8))
        self.render_globals_gbox.setTitle(QtGui.QApplication.translate("Dialog", "Render Globals", None, QtGui.QApplication.UnicodeUTF8))
        self.config_render_settings_button.setText(QtGui.QApplication.translate("Dialog", "Config Project Render Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.config_image_file_prefix_button.setText(QtGui.QApplication.translate("Dialog", "Config Project Image File Prefix", None, QtGui.QApplication.UnicodeUTF8))
        self.render_settings_gbox.setTitle(QtGui.QApplication.translate("Dialog", "Renderers Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.config_arnold_button.setText(QtGui.QApplication.translate("Dialog", "Config Project Arnold Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.config_redshift_button.setText(QtGui.QApplication.translate("Dialog", "Config Project Redshift Settings", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.config_tab), QtGui.QApplication.translate("Dialog", "Tab 1", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view_settings_tab), QtGui.QApplication.translate("Dialog", "Page", None, QtGui.QApplication.UnicodeUTF8))

from . import resources_rc
